name: Build GH-Pages

on:
  push:
    paths-ignore:
      - 'images/**'
      - 'LICENSE'
      - 'README.md'
    branches:
      - main
  workflow_dispatch:
    # manual run

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get Theme
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@c57490a8b04136ae58ab5866a93d3db2f0fa0945
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          pushd blog-src
          hugo --buildDrafts --gc --verbose --minify --templateMetrics --templateMetricsHints
          popd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@4eb285e828117bca26638192c3ed309c622e7bad
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./blog-src/public
